#!/bin/sh
set -e

cd /opt/couchbase
mkdir -p var/lib/couchbase \
         var/lib/couchbase/config \
         var/lib/couchbase/data \
         var/lib/couchbase/stats \
         var/lib/couchbase/logs \
         var/lib/moxi

chown -R couchbase:couchbase var
su - couchbase -c "/opt/couchbase/bin/couchbase-server -- -noinput"
