name: Publish Oracle JDK 8 Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'oraclejdk-8/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/oraclejdk-8
          tags: |
            type=raw,value=latest
            type=raw,value=8u201

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: oraclejdk-8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}